<?php

declare(strict_types=1);

namespace Database\Factories;

use App\Models\Course;
use App\Models\CourseMaterial;
use Illuminate\Database\Eloquent\Factories\Factory;

class CourseMaterialFactory extends Factory
{
    protected $model = CourseMaterial::class;

    public function definition(): array
    {
        return [
            'course_id' => Course::factory(),
            'title' => $this->faker->sentence(),
            'description' => $this->faker->optional()->paragraph(),
            'external_url' => $this->faker->optional()->url(),
            'file_path' => $this->faker->optional()->filePath(),
            'original_file_name' => $this->faker->optional()->word().'.pdf',
            'sort_order' => null, // will be generated by Model booted method
        ];
    }
}
